linters:
  disable-all: true
  enable:
    - gofumpt
    - staticcheck
    - govet
#    - gci
    - gofmt
    - goimports

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/Dreamacro/clash)
      - default
  staticcheck:
    go: '1.18'
